version: '3'

services:

  web:
#    image: mvuser_appmvuser:latest
    build: .
#    container_name: your container name here
    ports:
      - "3070:8080"
    depends_on:
      - postgres

  postgres:
    build: .docker/postgres
#    container_name: your container name here
    tty: true
    ports:
      - '5432:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_PASSWORD= your postgres password
#      - POSTGRES_DB= your postgres db name